### ISSUE TITLE
Folien Verbesserungsvorschläge

### ISSUE THREAD

**Issue by m1r3r1** [oelna/hsma-int#12]
Hallo!

Ich hätte ein bisschen was an den Folien zu meckern. Ich finde die Navigation durch die Folien in der Browseransicht etwas anstrengend.

-Eine Möglichkeit zur Übersicht der Themen zurückzuspringen (https://oelna.github.io/hsma-int-slides/#intro) wäre sehr praktisch,   ich würde manchmal gerne zurück zu dieser Startseite. Vielleicht könnte man eine Art Home Symbol einbauen.
Es wär auch gut über die Übersicht zu den Aufgaben zu den Themen bwz. die Seite https://github.com/oelna/hsma-int kommen zu können. 
Vielleicht liegt es nur an meinem Browser aber ich bin in den Folien "gefangen" und komm über die zurück-Tasten nicht wieder auf die Seite auf der ich zuvor war.

-Ich fände es auch nett wenn es noch eine weitere Möglichkeit gebe zur nächsten/vorherigen Folie zu klicken, z.B. durchs Klicken an den jeweils linken und rechten Rand der Folie. Ich habe eine kleine Tastatur ohne Pfeiltasten, für mich wäre das also praktischer! Aber ich hatte es auch schon rein intuitiv beim ersten Betrachten versucht so durch die Folien zu navigieren, aber es ging nicht :(

Vielen Dank

-Miriam

✽ ✾ ✿ ❀ ❁✽ ✾ ✿ ❀ ❁✽ ✾ ✿ ❀ ❁

**Comment by oelna** [comment]
Hi Miriam-

das sind super Hinweise, vielen Dank! Ein paar der Sachen hab ich auch selbst auf dem Radar, an andere hatte ich noch nicht gedacht. Ich behalts mal im Hinterkopf und schaue nach Lösungen dafür. Weil es das erste Semester ist, in dem ich die Folien als Website präsentiere und ausliefere, und ich die Stunden jeweils neu erstelle von Woche zu Woche, kann es am Anfang immer sein, dass Sachen noch nicht 100% ausgereift sind. Das ist natürlich nicht eure Schuld. Sollte es noch größere Probleme geben mit den Inhalten, gibt es ja auch noch die PDFs, die ich bisher immer zum Präsentieren verwendet habe: https://arnorichter.de/hsma/int
Die sind im Prinzip zu 96% identisch mit den neuen Folien und man kann die genau so gut hernehmen zum Wiederholen. Falls das hilft.

**Comment by oelna** [comment]
Ich hatte irgendwie Bock drauf, also hab ichs gemacht.

- Keyboard nav mit WASD zusätzlich zu den Pfeiltasten (W,A=zurück, S,D=vor)
- Schmale, klickbare Flächen am linken und rechten Rand für vor/zurück
- Uninspiriertes kleines Quadrat oben links, um auf die Übersicht zu kommen
-  Link zum Aufgaben-Repo auf der Übersicht.

Ist noch nicht alles 100%, aber ich denke, das sollte erstmal weiterhelfen.

**Comment by m1r3r1** [comment]
Entschuldigung, ich wollte früher darauf antworten.

Vielen lieben Dank für die Änderungen! Das navigieren durch die Folien ist nun viel angenehmer geworden :)
