### ISSUE TITLE
INT übung 4

### ISSUE THREAD

**Issue by Sophie-schoenig** [oelna/hsma-int#7]
[file:///C:/Users/Sophie/Aufgaben_HS/INT/%C3%9Cbung_4/index.html](url)

**Comment by oelna** [comment]
Zu spät gesehen, aber: Mit dem Link auf eine Datei in deinem lokalen Dateisystem kann ich leider nichts anfangen :|
Ich hoffe, wir konnten im Rahmen des Unterrichts über dein Anliegen sprechen!

**Comment by Sophie-schoenig** [comment]
Guten Tag, der Link war soweit ich das in Erinnerung habe zur Besprechung der Band Website Aufgabe zu Anfang des Semsesters,
meine fragen haben sich jedoch im laufe des Unterrichts geklärt und das besprechen der anderen Webseiten hat mir auch geholfen.


Von: Arno ***@***.***>
Gesendet: Mittwoch, 14. April 2021 18:51
An: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Betreff: Re: [oelna/hsma-int] INT übung 4 (#7)


Zu spät gesehen, aber: Mit dem Link auf eine Datei in deinem lokalen Dateisystem kann ich leider nichts anfangen :|
Ich hoffe, wir konnten im Rahmen des Unterrichts über dein Anliegen sprechen!
